---
- name: generate logrotate conf for {{ deploy_application_name }}
  become: yes
  template: >
    src=logrotate.conf.j2
    dest={{ deploy_logrotate_defaults.conf_dir }}/{{ deploy_application_name }}.conf
    owner=root
    group=root
    mode=0644
    validate='logrotate -df %s'
